### ISSUE TITLE
SSL Cert/Key Template

### ISSUE THREAD

**Issue by wesleytodd** [jfryman/puppet-nginx#126]
It looks like the template for ssl virtual hosts is not including the ssl cert and key correctly.  I am a total noob, so sorry if this is wrong and a waste of your time, but I applied a change to `templates/vhost/vhost_ssl_header.erb:10-11` and it appears to work for me now.  The change I made looks like this:

```
ssl_certificate           <%= @ssl_cert ? @ssl_cert : scope.lookupvar('nginx::params::nx_conf_dir') + '/' + @name.gsub(' ', '_') + '.crt' %>;
ssl_certificate_key       <%= @ssl_key ? @ssl_key : scope.lookupvar('nginx::params::nx_conf_dir') + '/' + @name.gsub(' ', '_') + '.key' %>;
```

If you want I can submit a PR, but I didn't want to unless this was an actually worthy change.  Let me know!  Thanks for the good work.

**Comment by 3flex** [comment]
Hi, please add any relevant comments to #599 regarding how the module will treat SSL certificates going forward. My proposal should mean this wouldn't be an issue anymore.
