### ISSUE TITLE
Allow to use multiple locations in vhost

### ISSUE THREAD

**Issue by jacek-berlin** [jfryman/puppet-nginx#189]
Hello,
Please correct me if I am wrong, now there is no possibility to declare multiple locations in one vhost ? 

Example output configuration:

http://doc.owncloud.org/server/5.0/admin_manual/installation/installation_others.html

**Comment by devopsdevon** [comment]
I would say this behavior is a bug.
If you have an SSL only vhost and a non-SSL location (or a non-SSL-only location), the module generates an invalid Nginx configuration that prevents the service from starting.

Having the module throw an error instead would be great.

**Comment by 3flex** [comment]
I'm closing this, as it looks like the original issue was addressed.

@devopsdevon would you open a new issue for the behaviour you described? Thanks!
