### ISSUE TITLE
Circular Dependency Error When referenced from another module

### ISSUE THREAD

**Issue by jbcpollak** [jfryman/puppet-nginx#244]
Hello,

I am using heira to manage my system configs, and have found multiple of my systems need a local nginx proxy, so I created a module with an init.pp that looks like this:

    class localproxy (
      $exthostname,
      $cfg_append = {}
      )
    {

      include ::nginx

      nginx::resource::upstream { 'local_app':
          ensure  => present,
          members => [
            'localhost:8080',
          ],
          require => [
            Class['::nginx'],
            Class['::nginx::package']
          ]
      }

      nginx::resource::vhost { "$exthostname" :
          ensure   => present,
          proxy    => 'http://local_app',
          location_cfg_append => $cfg_append,
      }
    }

When I run puppet, I get this error:

Error: Could not apply complete catalog: Found 1 dependency cycle:
(Anchor[nginx::end] => Class[Nginx] => Nginx::Resource::Upstream[local_app] => File[/etc/nginx/conf.d/local_app-upstream.conf] => Class[Nginx::Service] => Service[nginx] => Class[Nginx::Service] => Anchor[nginx::end])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

I have gone in circles (fitting I suppose), but am unable to figure out how to break this dependency cycle correctly.

**Comment by shadone** [comment]
I am hitting the same issue since recently, after experimenting a bit with different versions it seems 0.2.2 works fine for me but 0.2.3 triggers this.

**Comment by 3flex** [comment]
@shadone @bluecurio I've opened #609 to track your issue, which isn't the same as the one originally reported.

@jbcpollak are you still having problems here? I saw you have a workaround and the work to fix #609 is likely to improve the situation as well so if I don't hear back in a few days I'll close this.

**Comment by 3flex** [comment]
I'm closing this for now. @jbcpollak please comment if you have any information to add and I'll reopen. Thanks!
