### ISSUE TITLE
Add rewrite with if clause to puppet

### ISSUE THREAD

**Issue by hallemel** [jfryman/puppet-nginx#279]
Hi,
I need to add this rewrite lines into puppet
if '($remote_addr = !10.10.10.*){
rewrite ^(/(admin|hmc|cmscockpit)/)(.*) /maintenance/404.html
}

With following lines I can add in puppet the rewrites to the vhost file.
But I can't check the ip range I need.
location_cfg_append   =>  {
      'rewrite'   => '^(/(admin|hmc|cmscockpit)/)(.*) /maintenance/404.html
  },

Has anyone an Idea how I can add this lines in puppet for rewrite?

**Comment by 3flex** [comment]
I'm closing this for now as there are methods to add this code to the manifest. PRs are welcome to introduce cleaner support for `if` directives.
