### ISSUE TITLE
Storing SSH Keys and Certs in Hiera

### ISSUE THREAD

**Issue by thewellington** [jfryman/puppet-nginx#286]
I am storing my SSH Key and Cert in Hiera using an eyaml encrypted value.

I would like to be able to use the hiera variable in the ssl_key and ssl_vert fields, instead of providing file paths.

**Comment by khaefeli** [comment]
+1

we're storing our TLS keys / certs also in hiera and don't like them two times on the filesystem.
 
it would be also a nice if there is an option, to configure a folder for the certificates and not always $conf_dir/xy.crt 

if @jfryman would merge this options, I could work on a PR.

**Comment by jfryman** [comment]
I'd merge something like this. Totally agree with limiting the scope of where keys are. I'd actually love to see a defined type for SSL certs as opposed to embedding with the existing `vhost` resource.

**Comment by 3flex** [comment]
Hi, please add any relevant comments to #599 regarding how the module will treat SSL certificates going forward.
