### ISSUE TITLE
vhost: $rewrite_www_to_non_www

### ISSUE THREAD

**Issue by guyhughes** [jfryman/puppet-nginx#381]
Using latest github release https://github.com/jfryman/puppet-nginx/commit/61b569ca02e11a86c1abf647490b5f98a4aee03c on ruby 2.1.2p95 when `$rewrite_www_to_non_www => true,` in a vhost, having an array in `$server_name` goes wonky and only the first element of the array is handled.

Haven't investigated further. Only discovered that unsetting `$rewrite_www_to_non_www` removed the issue.

May be related to:
https://github.com/jfryman/puppet-nginx/pull/114
https://github.com/jfryman/puppet-nginx/pull/310
https://github.com/jfryman/puppet-nginx/pull/113

**Comment by 3flex** [comment]
@guyhughes I'm closing this as you said it seems to be resolved. If not please comment and I'll reopen. Cheers!
