### ISSUE TITLE
SSL certificate not found

### ISSUE THREAD

**Issue by tjoedden** [jfryman/puppet-nginx#397]
If there's an `nginx::resource::vhost` tag with more than two vhost addresses, the ssl certificates cannot be found.
this is because the `regsubst` function in `vhost.pp` line 326 to sanitize the copied ssl certificate filenames only replaces the first whitespace of the vhost name to form the certificate filename:
`$name_sanitized = regsubst($name, ' ', '_')`

Better would be something like:
`$name_sanitized = regsubst($name, ' ', '_', 'G') # all whitespaces replaced`
or even better
`$name_sanitized = regsubst($name, /\W/, '_', 'G') # all non-word characters replaced`

this should be checked against the `gsub` replacements in the `vhost_ssl_header.erb` template as well - right now all whitespaces are replaced there which is the cause why this failed.

**Comment by 3flex** [comment]
@tjoedden I'm closing this, if you have further information to add please reply and we can reopen.
