### ISSUE TITLE
Sendfile not fully configurable 

### ISSUE THREAD

**Issue by joboscribe** [jfryman/puppet-nginx#422]
Looks like sendfile was made configurable by 3387346d4beff527a530cd306d23136563e4a06c but then 5b28d0553d61cd347e1e9fa6f5f28e2994701ffe removed that. 

Without being able to explicitly set `sendfile off` on our Vagrant boxes we're running into those good old [known issues](https://docs.vagrantup.com/v2/synced-folders/virtualbox.html) with static files.

**Comment by 3flex** [comment]
Hi @joboscribe are you still running into this issue? I saw you weren't able to replicate, so if that's still the case I'm assuming this is no longer an issue for you.

**Comment by joboscribe** [comment]
I haven't been able to reproduce this issue lately. Closing.
