### ISSUE TITLE
"worker_connections must be an integer" error

### ISSUE THREAD

**Issue by the-andrew** [jfryman/puppet-nginx#537]
When attempting to install nginx (using the first example from the README) I am seeing this error. I have tried with the latest version of the plugin (from master) and also with the 0.0.10 version as I read on another thread.

In both cases, I get this error:

err: Could not retrieve catalog from remote server: Error 400 on SERVER: $worker_connections must be an integer

**Comment by mrmagcore** [comment]
Why are worker_connections, worker_rlimit_nofile and proxy_set_header required?  Couldn't they be left undef'd and set to nginx's own defaults?

**Comment by the-andrew** [comment]
I didn't specify this on the original post, but I was not actually passing any parameters for this class. The error was coming up when the defaults should have been used.

**Comment by eborned** [comment]
I'm still experiencing this issue with master 3.7.2-4, puppetlabs-stdlib v4.9.0 and the v0.3.0 version of this plugin. Any specific reason why the config.pp doesn't just use the integer values instead of the strings?
