### ISSUE TITLE
Symlink happening after service refresh

### ISSUE THREAD

**Issue by gwagner** [jfryman/puppet-nginx#541]
It appears that the symlink from sites-available to sites-enabled is happening after the service gets refreshed.  This is problematic as we need to bounce nginx manually (unless we make another subsequent change to the configs and re-run puppet)

**Comment by steakknife** [comment]
@gwagner Try

 `sed -i -e "s/Service\['nginx'\]/Class\['::nginx::service'\]/" manifests/resource/vhost.pp`

**Comment by gwagner** [comment]
Should i update to the latest master first?

**Comment by steakknife** [comment]
Could give that a go.  If you're using librarian, just add a git option to the end of the dependency.

—

**Comment by steakknife** [comment]
Could give that a go.  If you're using [librarian](http://librarian-puppet.com/), just add a git option to the end of the dependency and run `librarian-puppet update`.

(Email gateway comments are always plaintext.)
