### ISSUE TITLE
new tag?

### ISSUE THREAD

**Issue by soniah** [jfryman/puppet-nginx#547]
Hi, thanks for writing this module.

Would it be possible to tag the more recent work? The last tag (0.2.1) is quite a while ago...

**Comment by skorten** [comment]
+1

I'm running off tip of master right now and would much prefer a "stable" tag.

**Comment by jfryman** [comment]
This is on my list for the weekend work.

**Comment by soniah** [comment]
Thanks James. I know what it's like with open source projects - evenings, weekends :-)

**Comment by jfryman** [comment]
New version https://github.com/jfryman/puppet-nginx/releases/tag/v0.2.2 tagged and published on the forge.

**Comment by skorten** [comment]
Thanks!
