### ISSUE TITLE
Example hiera configuration doesn't work

### ISSUE THREAD

**Issue by split3** [jfryman/puppet-nginx#558]
Using the hiera configuration from the documentation for configuration of a location doesn't appear to work

```
nginx::nginx_locations:
  'some-service-ext':
    location: /myservice
    vhost: 'service-ext'
```

When using the sample configuration puppet will give an error of:

**Cannot create a location reference without a www_root, proxy, location_alias, fastcgi, stub_status, internal, or location_custom_cfg defined**

Currently I'm using v0.2.2

**Comment by 3flex** [comment]
As the error says, you need to specify at least one of:
* www_root
* proxy
* location_alias
* fastcgi
* stub_status
* internal
* location_custom_cfg

You've only specified `location` and `vhost` in your example, hence the error.

I can see the faulty example in the README though and will update. Thanks for pointing that out!
