### ISSUE TITLE
Deprecation warning for parameters

### ISSUE THREAD

**Issue by gavinrogers** [jfryman/puppet-nginx#564]
Hi, thanks for the great module.

This warning:

```shell
==> puppetmasterlocal: Notice: [nginx] *** DEPRECATION WARNING***: HI! I notice that you're declaring some attributes in Class[nginx]. It 
is highly recommended to set these values via Hiera going forward. This will become mandatory in the near future. Please check out https:/
/github.com/jfryman/puppet-nginx/blob/master/docs/hiera.md for more information.
==> puppetmasterlocal: Notice: /Stage[main]/Nginx::Notice::Config/Notify[[nginx] *** DEPRECATION WARNING***: HI! I notice that you're decl
aring some attributes in Class[nginx]. It is highly recommended to set these values via Hiera going forward. This will become mandatory in
 the near future. Please check out https://github.com/jfryman/puppet-nginx/blob/master/docs/hiera.md for more information.]/message: defin
ed 'message' as '[nginx] *** DEPRECATION WARNING***: HI! I notice that you're declaring some attributes in Class[nginx]. It is highly reco
mmended to set these values via Hiera going forward. This will become mandatory in the near future. Please check out https://github.com/jf
ryman/puppet-nginx/blob/master/docs/hiera.md for more information.'
```

- In this case, another module is parameterizing Class::nginx (specifically, [this feature branch](https://github.com/gavinrogers/puppetmodule/tree/feature-nginx) 

So I don't see any sense in the error message, or in ever dropping support for doing this? Unless there is some way that modules can dynamically set hiera values (that's would be cool, but going down the rabbit hole a bit).

**Comment by 3flex** [comment]
I think the answer is to to declare `nginx::config` and set parameters there instead of declaring `nginx` class.

There's more discussion of jfryman's rationale here: https://github.com/jfryman/puppet-nginx/issues/536#issuecomment-68398665

**Comment by 3flex** [comment]
@gavinrogers did this help at all? Are you still having issues?

**Comment by pscadiz** [comment]
+1 on this issue, i am a user of the module (and branch) raised by @gavinrogers 
The declaration of class nginx is placed in the module itself, so users will have the same warning once they use the module.

Is there a way for me, as a user, to override the module declaration to avoid the deprecation warning? Or is the only solution actually changing the declaration in the module?

**Comment by ElvenSpellmaker** [comment]
We've had to fork this module at work and remove the deprecation notice. While puppet doesn't support `::params` any more, it _does_ suggest that values may be overridden as parameters, something which this module doesn't support. (https://docs.puppet.com/puppet/latest/reference/lookup_quick_module.html#example-with-hiera)

```pp
# ntp/manifests/init.pp
# ntp/manifests/init.pp
class ntp (
  # default values are in ntp/data
  $autoupdate
  $service_name
) {
 ...
}
```
Note that `$autoupdate` and `$service_name` are parameters that are valid for overriding if you want to and that the page mentions nothing about stopping people from being able to override them.

This is annoying for us as we (obviously) have several different types of web server and not all are configured exactly the same, and we don't want to end up with one hiera file per `role` or machine just for this if we can help it.

The thing is, `::params` inheritance is deprecated ***not*** the ability to pass parameters to the class itself.
