### ISSUE TITLE
Configure passenger through hiera.

### ISSUE THREAD

**Issue by ctavan** [jfryman/puppet-nginx#568]
I've tried to configure the pre-built passenger packages through hiera but I seem to be missing something.

The following puppet config works for me as expected:

```puppet
  class { 'nginx':
    package_source  => 'passenger',
  }
```

I tried to transform this into the puppet part:

```puppet
include nginx
```

and the hiera part:

```yaml
---
nginx::package:
  package_source: 'passenger'
```

However the puppet-nginx module doesn't respect the hiera config. Am I using the wrong keys in hiera?

EDIT: I have modified my initial comment. Initially I was wondering about `nginx::config::http_cfg_append` as well, but this works fine. So my final question is only concerned about the `package_source`.

**Comment by 3flex** [comment]
Use this in hiera:
```yaml
---
nginx:
  package_source: 'passenger'
```

The reason is a resource-like declaration is being used to declare `nginx::package` in `init.pp`. That overrides whatever you set in hiera for `nginx::package`. Instead, set `package_source` on `nginx` class as in my example.

**Comment by 3flex** [comment]
There's info here about the automatic parameter lookup rules: https://docs.puppetlabs.com/hiera/1/puppet.html#automatic-parameter-lookup

**Comment by ctavan** [comment]
@3flex thanks for your answer. Unfortunately your suggestion didn't work for me either. However following the documentation I managed to figure out the correct hiera config:

```yaml
---
nginx::package_source: 'passenger'
```

That works for me with puppet 3.7.4 and hiera 1.3.4 and jfryman-nginx v0.2.6.
