### ISSUE TITLE
vagrant vhost files

### ISSUE THREAD

**Issue by rarutu** [jfryman/puppet-nginx#577]
hi

i ma using vagrant with centos 7 and when puppet tries to create the vhost i get this error:

Notice: /Stage[main]/Main/Nginx::Resource::Vhost[www.puppetlabs.com]/Concat[/etc/nginx/sites-available/www.puppetlabs.com.conf]/Exec[concat_/etc/nginx/sites-available/www.puppetlabs.com.conf]/returns: sh: /var/lib/puppet/concat/bin/concatfragments.sh: /bin/sh^M: bad interpreter: No such file or directory
Error: /var/lib/puppet/concat/bin/concatfragments.sh -o "/var/lib/puppet/concat/_etc_nginx_sites-available_www.puppetlabs.com.conf/fragments.concat.out" -d "/var/lib/puppet/concat/_etc_nginx_sites-available_www.puppetlabs.com.conf" returned 126 instead of one of [0]
Error: /Stage[main]/Main/Nginx::Resource::Vhost[www.puppetlabs.com]/Concat[/etc/nginx/sites-available/www.puppetlabs.com.conf]/Exec[concat_/etc/nginx/sites-available/www.puppetlabs.com.conf]/returns: change from notrun to 0 failed: /var/lib/puppet/concat/bin/concatfragments.sh -o "/var/lib/puppet/concat/_etc_nginx_sites-available_www.puppetlabs.com.conf/fragments.concat.out" -d "/var/lib/puppet/concat/_etc_nginx_sites-available_www.puppetlabs.com.conf" returned 126 instead of one of [0]

from the research i did i think it is due to the file ending conflict between windows and unix system but i have no solution :(

thanks,
rarutu

**Comment by 3flex** [comment]
This looks like a problem with your installation of puppetlabs-concat, not this module.

Which version of puppetlabs-concat do you have installed? How did you install it?

**Comment by 3flex** [comment]
I'm closing this for now. @rarutu please comment if you have any information to add and I'll reopen. Thanks!
