### ISSUE TITLE
ssl vhost gives error 

### ISSUE THREAD

**Issue by nathan-copperfrog** [jfryman/puppet-nginx#585]
When I try to setup a vhost with ssl => true i get the below error. 

Error 400 on SERVER: 800 is not a string.  It looks to be a Fixnum at /opt/puppet/share/puppet/modules/concat/manifests/fragment.pp:43

I raced the problem to nginx/manifests/resource/location.pp:375 
order   => $ssl_priority,

If I change it to 

order   => $ssl_priority",

The module works as expected. Is there a setup in the vhost I am missing or is this an actual bug? My vhost is below

**Comment by 3flex** [comment]
I expect you're using an out of date version of puppetlabs-concat. This module requires 1.1.1 to be installed.

Can you confirm the version of this module and the version of puppetlabs-concat that you're using?

**Comment by 3flex** [comment]
I'm closing this for now. @nathan-copperfrog please comment if you have any information to add and I'll reopen. Thanks!
