### ISSUE TITLE
'undef' from left operand of 'in' expression is not a string at /etc/puppet/modules/nginx/manifests/params.pp:23

### ISSUE THREAD

**Issue by sangm** [jfryman/puppet-nginx#601]
Getting this error when running on a fresh new install of Debian 7 on DigitalOcean node

` class { 'nginx': } `

` or ($::operatingsystem == 'debian' and $::operatingsystemmajrelease in ['6', '7']) {
        $_module_os_overrides = {
          'manage_repo' => true,
          'daemon_user' => 'www-data',
        }
`
I presume operatingsystemmajrelease is undefined for some reason. Deleted that line and it worked great

**Comment by 3flex** [comment]
@sangm which version of Facter are you using? If it's the one packaged by Debian it would be 1.6.10 while this module requires 1.7.0 or higher.

`operatingsystemmajrelease` fact was added in 1.7.0.

**Comment by 3flex** [comment]
I'm closing this for now. @sangm please comment if you have any information to add and I'll reopen. Thanks!
