### ISSUE TITLE
Latest version no longer works on DragonFlyBSD

### ISSUE THREAD

**Issue by strangelittlemonkey** [jfryman/puppet-nginx#619]
Partially due to the params.pp being used now and not mentioning DragonFly, which I can fix in a couple minutes, but something deeper was changed that's now generating an invalid config even when that's not an issue. I'll try to get it functional again and send a pull request. Any help along the way would be greatly appreciated.

**Comment by strangelittlemonkey** [comment]
Ok. It seems if you don't have a /var/log/nginx directory it will not make one, but instead just fail. Should I address that in the pull request as well?

**Comment by 3flex** [comment]
Did some research: Dragonfly is a fork of FreeBSD. In FreeBSD the following log files are used for nginx by default:

* Access log: `/var/log/nginx-access.log`
* Error log: `/var/log/nginx-error.log`

I'd expect DragonFly to be the same. So what should happen ideally is that the logdir is set to `/var/log` for both FreeBSD and DragonFlyBSD to reflect the distribution default, and the default log file names should be as above. There should be no need for this module to create a log directory in this case.

Are you up to creating a PR to cover that?

**Comment by strangelittlemonkey** [comment]
When I put 'FreeBSD', 'DragonFlyBSD':, it wanted to make /var/log/nginx/[access|error].log. I can take care of that too though.

**Comment by 3flex** [comment]
@strangelittlemonkey not sure if you're still working on this, but there's active conversation in #635 and I don't want your submission and #635 to duplicate any work!
