### ISSUE TITLE
SSL Self signed cert

### ISSUE THREAD

**Issue by b4ldr** [jfryman/puppet-nginx#630]
Hi I noticed a lot of chatter about SSL in the past month which reminded me that i had created a self_signed cert type for use internally.  I have uploaded it to github[1] and wondered if this is something that would be of use to have in nginx.  Its only tested on ubuntu at the moment so some of the paths would need some work for other systems.  Let me know what you think if its f use ill happily make some updates

[1]https://github.com/b4ldr/puppet-self_signed_cert

**Comment by 3flex** [comment]
hi @b4ldr, thanks for the tip!

We haven't discussed this functionality, but personally I think if we were going to introduce something like that we'd probably look at integrating with the camptocamp openssl module, which covers the same ground but also has the benefit of being a Puppet Approved module so most likely to be supported going forward.

That said, I also don't think it's a great idea to have this module integrate the SSL key management. Everyone does it differently so it's best for individual sites to come up with their own solution IMHO.

@jfryman may have other ideas though.

**Comment by b4ldr** [comment]
Thanks for the pointer i hadn't seen 'camptocamp openssl module' when i wrote mine, i will probably switch to that myself.  I also had similar thoughts on ssl management been integrated into this module so i will gracefully pull back :)
