### ISSUE TITLE
Unable to validate module on servers not using it

### ISSUE THREAD

**Issue by frachonl** [jfryman/puppet-nginx#631]
Hello,

I'm using nginx for part of my servers, others using Apache for other purposes.

When not including the Nginx module (either class::nginx or include ::nginx)  in the server's conf, I'm unable to deploy it as it complains about 'err: Could not retrieve catalog from remote server: Error 400 on SERVER:  is not valid. It should be 4 digits (0644 by default). at /etc/puppet/environments/****/modules/nginx/manifests/resource/vhost.pp:428 on node *****.******.**'

Puppet 2.7, Debian 7

And if I include it, it then fails starting because port 80 is already in use.

What part should I include or declare for having something working ?

Thanks

**Comment by 3flex** [comment]
@frachonl you need to include the `nginx` class. You can configure the port by setting `listen_port` to something other than `80` on the `nginx::resource::vhost` declaration.

**Comment by frachonl** [comment]
Great.... Using unneeded resources. Thanks anyway...
