### ISSUE TITLE
upgrade to puppetlabs/apt >= 2.0.0

### ISSUE THREAD

**Issue by bhechinger** [jfryman/puppet-nginx#646]
There are other modules I use that want >= 2.0.0 and I was wondering if it wasn't too much trouble would you be able to make your module compatible with the 2.x line?

**Comment by 3flex** [comment]
@bhechinger It actually is in git since https://github.com/jfryman/puppet-nginx/pull/612 was merged, we just need @jfryman to push a new release to Forge.

**Comment by jfryman** [comment]
I'm on it. Standby.

**Comment by jfryman** [comment]
[`0.2.7`](https://forge.puppetlabs.com/jfryman/nginx) released to the forge.
