### ISSUE TITLE
Invalid parameter options on Apt_key[Add key: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 from Apt::Source nginx]

### ISSUE THREAD

**Issue by bhechinger** [jfryman/puppet-nginx#650]
Do you have any idea with this is?

This started once I upgraded to puppetlabs/apt 2.1.0 and your 0.2.7

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter options on Apt_key[Add key: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 from Apt::Source nginx] at /etc/puppetlabs/puppet/environments/production/modules/apt/manifests/key.pp:84

**Comment by 3flex** [comment]
Do you have pluginsync set correctly? Looks like it's saying "options" is not a valid value when called internally by puppetlabs-apt module. But it's definitely available on the `apt_key` type in puppetlabs-apt 2.x.

**Comment by bhechinger** [comment]
root@puppet1:~# grep pluginsync /etc/puppetlabs/puppet/puppet.conf
    pluginsync = true

**Comment by 3flex** [comment]
Not sure what's going on here, we have a spec test that would hit that code and it's passing OK.

I saw you raised https://github.com/fsalum/puppet-newrelic/issues/39, I'd suggest perhaps asking on the puppet-users mailing list to see if anyone else is running into the issue as it may be specific to your setup or the puppetlabs-apt module.

Could you also try with puppetlabs-apt 2.0.0 or 2.0.1? There were some changes made to add backwards compatibility with puppetlabs-apt 1.8.x series in 2.1.0 which may have tripped things up.

**Comment by mwillbanks** [comment]
@bhechinger you likely updated puppetlabs/apt but failed to update puppetlabs/stdlib - I ran into the same exact thing.

**Comment by mvisonneau** [comment]
@mwillbanks I have the exact same problem with puppetlabs/apt:2.1.0 and puppetlabs/stdlib:4.6.0 :/

**Comment by Hufschmidt** [comment]
We are having the same issue, using manage_repo=false for now.

"name": "puppetlabs-apt",
"version": "2.1.0",

"name": "jfryman-nginx",
"version": "0.2.7",

"name": "puppetlabs-stdlib",
"version": "4.6.0",

**Comment by raoulbhatia** [comment]
I had a similar issue after upgrading various puppet modules,
but with the apt::backports class and not this one.

A restart of the puppet master resolved the issue for me.

Maybe this would be worth a shot?

**Comment by Hufschmidt** [comment]
Rebooting also fixed the problem for us, according to our sys-admin, the Puppetserver seems to not update (or more specifically reload) module-providers after a module update.

This means, while the module was updated, the puppetmaster is still working with the old (cached) version until restarted.

**Comment by mvisonneau** [comment]
Yes indeed, it worked for me too. Good to know though !

**Comment by ctavan** [comment]
Same here: puppetlabs/apt:2.1.0 and puppetlabs/stdlib:4.6.0 -> Restart of puppetmaster helped.

**Comment by 3flex** [comment]
@bhechinger can you see if a reboot resolves things?

**Comment by maxenced** [comment]
I can confirm I run into exact same issue and restart of puppetserver solved the stuff for me too.

**Comment by 3flex** [comment]
Sounds like we have consensus here that this is a bug with the Puppet Server implementation rather than this module.

Thanks everyone for the feedback!

**Comment by murnieza** [comment]
Restarting puppet master solved this problem for me.

**Comment by strarsis** [comment]
I also ran into the same issue - but I don't use a puppet server but masterless puppet (puppet apply).
