### ISSUE TITLE
Deprecation warning when adding worker_processes through hiera

### ISSUE THREAD

**Issue by ege1** [jfryman/puppet-nginx#655]
Hi,

as soon as I set 
nginx::worker_processes: 2

Through hiera, I get the deprecation warning:

Notice: [nginx] *** DEPRECATION WARNING***: HI! I notice that you're declaring some attributes in Class[nginx]. It is highly recommended to set these values via Hiera going forward. This will become mandatory in the near future. Please check out https://github.com/jfryman/puppet-nginx/blob/master/docs/hiera.md for more information.

I just removed the check for worker_processes to get around this message (because otherwise foreman always reports changes on the host), so this is not an issue to me.

So just so you know.

Kind Regards,

Erik

**Comment by PierreR** [comment]
:+1:  Same issue for me see referenced issue :-(

**Comment by 3flex** [comment]
@ege1 does the error go away when you set it like this?
```yaml
nginx::config::worker_processes: 2
```

**Comment by PierreR** [comment]
@ege1 I am pretty sure It does not work with `nginx::config::worker_processes` (see #536) It is silently ignored (but yes the deprecation warning disappears)

**Comment by 3flex** [comment]
@jfryman might need to come up with an alternate solution that is a bit more robust than what we have at the moment... I agree the warning is not ideal in this case, and I'm not sure how best to re architect things to both match @jfryman's goals for the module's structure and also make things more user friendly.

**Comment by ege1** [comment]
@3flex Thanks for that hint. Yes, that works just perfect for me. It is recognized and it stops the deprecation warning. And i do not have explicitly included the nginx::config

So for me this is solved that way.
