### ISSUE TITLE
Misinterpretation of puppet-module-data

### ISSUE THREAD

**Issue by mlehner616** [jfryman/puppet-nginx#663]
I'm not able to use defined types against this module because it **requires** I use my global hiera-archy which actually will not work. The goal of the rewrite of this module was to move towards `puppet-module-data` but I believe the definition of `puppet-module-data` was misinterpreted. The logic in this module is simply broken. I'm getting deprecation warnings regardless of how my resources are defined. The module does not work as documented.

If we're moving to `puppet-module-data` there should be a /data directory _inside_ the module with the hiera data within that. What you appear to be doing here is simply making another assumption that the consumer will be using hiera and thus forcing them to define defaults globally which is not always the case and using hiera **should never** be mandatory. The deprecation warning conditional will always be true based on the current architecture.

puppet-module-data implementation is clearly laid out here: https://www.devco.net/archives/2013/12/08/better-puppet-modules-using-hiera-data.php

**Comment by jfryman** [comment]
We're not going that way anymore.

https://github.com/jfryman/puppet-nginx/pull/501
