### ISSUE TITLE
Wildcard domain

### ISSUE THREAD

**Issue by AlmogBaku** [jfryman/puppet-nginx#668]
Is it possible to define a wildcard domain, such as:
```
    server_name           => "*",
```

If i'm right it'll create a file named `*.conf` which will probably break the system.

**Comment by 3flex** [comment]
nginx doesn't have the concept of wildcard domains like this, see this documentation from http://nginx.org/en/docs/http/server_names.html#miscellaneous_names:

> nginx versions up to 0.6.25 supported the special name “\*” which was erroneously interpreted to be a catch-all name. It never functioned as a catch-all or wildcard server name. Instead, it supplied the functionality that is now provided by the server_name_in_redirect directive. The special name “*” is now deprecated and the server_name_in_redirect directive should be used. Note that there is no way to specify the catch-all name or the default server using the server_name directive. This is a property of the listen directive and not of the server_name directive.

So you are correct in saying that this won't work. What are you trying to achieve?

**Comment by mig5** [comment]
You probably want to create one with 

```
server_name _; 
```

with the listen_options parameter set to 'default', this would probably create a 'catch all' domain (if that is your intention).

**Comment by 3flex** [comment]
Closing this for now, as wildcard `*` domains are not supported in nginx so won't be supported by this module.
