### ISSUE TITLE
fastcgi.erb doesn't include rewrite_rules. Why?

### ISSUE THREAD

**Issue by rogerlz** [jfryman/puppet-nginx#674]
Why $rewrite_rules isn't included into fastcgi.erb? Is this intentional?

**Comment by 3flex** [comment]
@rogerlz I'm not sure what that configuration might look like... but the file that's provided by the module should be identical to (or very closely match) the file provided upstream. Any rewrite rules can be specified outside of the fastcgi configuration file.
