### ISSUE TITLE
warning/notice about hiera?

### ISSUE THREAD

**Issue by nschloe** [jfryman/puppet-nginx#677]
I noticed that this module recommends usage of Hiera by issuing the "warning" (it's marked as a `notice` in the actual output) 
```
manifests/notice/config.pp:  $message = "[nginx] *** DEPRECATION WARNING***: HI! I notice that you're declaring some attributes in Class[nginx]. It is highly recommended to set these values via Hiera going forward. This will become mandatory in the near future. Please check out https://github.com/jfryman/puppet-nginx/blob/master/docs/hiera.md for more information."
```
When browsing through the sources, I couldn't find any place where puppet-nginx makes explicit use of hiera. Am I missing something?
In reality, I think it's correct that the module makes no assumptions about how and where the data is provided. That leaves the question of why puppet-nginx makes this recommendation.

**Comment by b4ldr** [comment]
Did you read the link it explains why this is been changed and also gives a recommendation on how to configure this without hiera

**Comment by nschloe** [comment]
I did. I guess I was taken aback by the fact that puppet-nginx explicitly endorses a particular data model (Hiera) while in reality [it shouldn't care](http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-1/).

In any case, if you think that this remark is invalid, feel free to close.
