### ISSUE TITLE
Why worker_processes isn't set at processorcount by default?

### ISSUE THREAD

**Issue by jlory** [jfryman/puppet-nginx#679]
Hi,

Is there a reason why worker_processes isn't set to the number of actual cores of the machine? Using the puppet fact processorcount, it's pretty easy to get.

Regards,

**Comment by jfryman** [comment]
It is not reasonable to assume that all cores will go to Nginx usage, as it could sit on a shared box. This is a user configurable item that you can set using the same logic.
