### ISSUE TITLE
http2 support

### ISSUE THREAD

**Issue by nunnun** [jfryman/puppet-nginx#690]
http2 is supported since 1.9.5 and spdy is superseded by http2.
https://www.nginx.com/blog/nginx-1-9-5/
before 1.9.5 spdy still should be supported

     spdy                => 'on',

after 1.9.5

     http2                => 'on',

and real configuration should be

     listen 443 ssl http2 default_server;

**Comment by jfryman** [comment]
Any chance you could put together a PR? Would happily review and merge.

**Comment by 3flex** [comment]
Fixed in #703
