### ISSUE TITLE
proxy.conf.erb seems to be missing

### ISSUE THREAD

**Issue by mickaelperrin** [jfryman/puppet-nginx#694]
Hi,

In config.pp, we can find 

    $proxy_conf_template            = 'nginx/conf.d/proxy.conf.erb',

but the directory templates/conf.d does not contain that file.

Am I missing something ?

I discovered this issue when trying to use the [puppet-nginx-hardening](https://github.com/hardening-io/puppet-nginx-hardening) module.

Regards,

**Comment by 3flex** [comment]
Hmm this is caused by an incomplete patch in https://github.com/jfryman/puppet-nginx/pull/642.

That line in `config.pp` is being ignored and the puppet-nginx-hardening module should not override that file because it no longer exists.

**Comment by 3flex** [comment]
I've raised an issue on that module: https://github.com/hardening-io/puppet-nginx-hardening/issues/9

**Comment by mickaelperrin** [comment]
OK, thanks for the information.

I finally extracted the "hardening" configuration part of the module and inject it directly as configuration in my manifest.
