### ISSUE TITLE
Puppet 4 support?

### ISSUE THREAD

**Issue by apazga** [jfryman/puppet-nginx#696]
Do you have in mind adding support for Puppet version 4.X?

Thanks in advance!

**Comment by jfryman** [comment]
I use this module day in and out with 4.2. Is there something not working?

**Comment by apazga** [comment]
Oh! Great! I didn't try to install it in my new Puppet 4.2 environment.
I was just asking because in "Compatibility" tab there is just Puppet 3.X (Enterprise or not).

Did you try using it with Debian 8 too?

Thanks @jfryman.

**Comment by jfryman** [comment]
@apazga absolutely! Works with Debian 8. Let me know if you run into issues. Cheers!
