### ISSUE TITLE
Folders beeing created before the package is installed.

### ISSUE THREAD

**Issue by jlory** [jfryman/puppet-nginx#704]
I'm using the last version of the module without Hiera bindings so I'm using Anchor ( like in the example )
The problem is when the first Puppet run starts I get: 

Error: Could not set 'directory' on ensure: Could not find user nginx at 204:/opt/git/puppet/modules/nginx/manifests/config.pp
Error: Could not set 'directory' on ensure: Could not find user nginx at 204:/opt/git/puppet/modules/nginx/manifests/config.pp

In the example class { 'nginx::config': } is above class { 'nginx' } so the folders are created before the Nginx package is installed.

Am I missing something?

**Comment by blsmth** [comment]
what was your resolution on this?
