### ISSUE TITLE
nginx repo key too short

### ISSUE THREAD

**Issue by richardrasu** [jfryman/puppet-nginx#714]
Hi,

We get complaints from our machines when they touch nginx;
Add key: 7BD9BF62 from Apt::Source nginx]) The id should be a full fingerprint (40 characters), see README.

According to output of apt-key finger, the full fingerprint for nginx is:
573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62

which should be managed by nginx :: package :: debian (excuse the spacing inbetween the colons, had issues with unwanted emoji)- is this enough info for a change, or should I fork & issue a PR? 

Cheers

Richard

**Comment by 3flex** [comment]
@richardrasu which version of the module are you using? The full fingerprint was added in https://github.com/jfryman/puppet-nginx/commit/d9b1d8cf8c35a810c2ac38544329975eef68f69f

This is available in versions 0.2.4 and up.

**Comment by richardrasu** [comment]
@3flex oof, that's embarrassing - I *thought* we were on the latest version. I'll check shortly.
Many Apologies!

R.
