### ISSUE TITLE
Circular dependency when setting daemon_user and super_user

### ISSUE THREAD

**Issue by kostecky** [jfryman/puppet-nginx#728]
When setting `super_user = true` and `daemon_user = 'deploy'` a dependency cycle happens that breaks the `puppet apply`. I've attached the cycle dependency graph as well as the error.

Puppet client version: 4.3.0

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Anchor[nginx::end] => Class[Nginx] => User[deploy] => File[/var/nginx/client_body_temp] => Class[Nginx::Config] => Class[Nginx::Service] => Service[nginx] => Class[Nginx::Service] => Anchor[nginx::end])
Cycle graph written to /opt/puppetlabs/puppet/cache/state/graphs/cycles.dot.
```

![cycles](https://cloud.githubusercontent.com/assets/159611/11730026/68afa5f6-9f60-11e5-9622-caace578e635.png)

**Comment by kostecky** [comment]
I believe this is an issue on my end, my apologies.

**Comment by jfryman** [comment]
@kostecky no worries. glad you got it sorted!
