### ISSUE TITLE
manage_repo => false feature is not available

### ISSUE THREAD

**Issue by anishnath** [jfryman/puppet-nginx#731]
The Issue is in the private VM where where the outbound internet access is not there this module is failed to install nginx, In my deployment the repo is managed by another VM where nginx rpm are served

class { 'nginx': manage_repo => false
  }

nginx::resource::vhost { 'www.puppetlabs.com':
  www_root => '/var/www/www.puppetlabs.com',
}

[root@bashec2-user]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for ph-dlife-nva-staging-ds-05.ph.com
Info: Applying configuration version '1450360681'
Notice: /Stage[main]/Nginx::Package::Redhat/Yumrepo[nginx-release]/ensure: created
Info: changing mode of /etc/yum.repos.d/nginx-release.repo from 600 to 644
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install nginx' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nginx-release. Please verify its path and try again
Error: /Stage[main]/Nginx::Package::Redhat/Package[nginx]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install nginx' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nginx-release. Please verify its path and try again
Info: Class[Nginx::Package::Redhat]: Unscheduling all events on Class[Nginx::Package::Redhat]

**Comment by tux-o-matic** [comment]
Duplicate of https://github.com/jfryman/puppet-nginx/issues/653 which might have the answer for you, try combinding manage_repo=> false with package_ensure=> 'absent'

**Comment by anishnath** [comment]
Thanks
