### ISSUE TITLE
Unable to connect to Upstart Ubuntu 15.10

### ISSUE THREAD

**Issue by richardmcsong** [jfryman/puppet-nginx#734]
Hi, while running "include nginx" it returns this error:

 Error: /Stage[main]/Nginx::Service/Service[nginx]: Could not evaluate: Execution of '/sbin/status nginx' returned 1: status: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Error: /Stage[main]/Nginx::Service/Service[nginx]: Failed to call refresh: Execution of '/sbin/status nginx' returned 1: status: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Error: /Stage[main]/Nginx::Service/Service[nginx]: Execution of '/sbin/status nginx' returned 1: status: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

I know Ubuntu 15 relies on systemd now... is there a way to get puppet to use systemctl status nginx?

**Comment by 3flex** [comment]
This should be handled by Puppet itself (it should try using systemd on supported systems). This module's not doing anything custom with the service unless `configtest_enable` parameter is set to true, but I don't think that's what's happening here.

Are you using Puppet from the distro or upstream? Which version?

**Comment by richardmcsong** [comment]
im using the puppet from the distro, version 3.7.2

**Comment by 3flex** [comment]
Are you being affected by this bug? https://bugs.launchpad.net/ubuntu/+source/puppet/+bug/1457957

**Comment by richardmcsong** [comment]
hmm good point! i aliased my status, start and end commands... and puppet doesn't seem to be erroring anymore. Thanks!
