### ISSUE TITLE
README not helping as much as it could to create a reverse proxy

### ISSUE THREAD

**Issue by alexharv074** [jfryman/puppet-nginx#751]
I had a simple requirement to proxy port 80 through to a Kibana 4 application running on localhost:5601.

The README seems to imply that I need to do something like this:

```
include nginx
nginx::resource::upstream { $::fqdn:
  members => [ 'localhost:5601' ],
}
nginx::resource::vhost { $::fqdn:
  proxy => "http://${::fqdn}",
}
```

(By the way, this led to a very unhappy Nginx that had lots of `(24: Too many open files)` messages when I tried to connect to it.)

I found the answer in the tests directory:

```
include nginx
nginx::resource::vhost { "${::fqdn}:80":
  ensure      => present,
  listen_port => 80,
  server_name => ["${::fqdn} ${::hostname}"],
  proxy       => 'http://localhost:5601',
}
```

which can be simplified to:

```
include nginx
nginx::resource::vhost { "${::fqdn}:80":
  proxy       => 'http://localhost:5601',
}
```

I would recommend making the documentation clearer for this simple use-case.

**Comment by jfryman** [comment]
@alexharv074 Think you could submit a PR with a better example? Would be great to have that captured for others in the future. :pray: and :bow:

**Comment by alexharv074** [comment]
PR raised https://github.com/jfryman/puppet-nginx/pull/752
