### ISSUE TITLE
Could not retrieve nginx_version: uninitialized constant Facter::Core

### ISSUE THREAD

**Issue by alexharv074** [jfryman/puppet-nginx#758]
I suspect that someone's added a custom fact that's only compatible with certain versions of facter.  

```
[root@centos-66-x64 ~]# facter -v
1.7.3
[root@centos-66-x64 ~]# puppet apply -e 'include nginx'
Could not retrieve nginx_version: uninitialized constant Facter::Core
Could not retrieve nginx_version: uninitialized constant Facter::Core
...
```

**Comment by 3flex** [comment]
Thanks, you're right... this was added in #753. I'm going to revert that change and ask that the fact be made compatible with earlier versions, or if not, bump the Facter version dependency.

**Comment by jyaworski** [comment]
Is this the facter from EPEL?

**Comment by alexharv074** [comment]
It's not from EPEL; it's just Facter 1.7.3 installed as a Gem when I installed Puppet 3.3.1.  It seems like Puppet hates us, because looks like they moved stuff in Facter::Util::Resolution to Facter::Core::Execution when they released Facter 2.
