### ISSUE TITLE
WARNING: The $ensure parameter to concat::fragment is deprecated and has no effect

### ISSUE THREAD

**Issue by TJM** [jfryman/puppet-nginx#776]
When using puppetlabs-concat > 2.0, you get the following warning when creating a vhost:

```
Warning: Scope(Concat::Fragment[(redacted)]): The $ensure parameter to concat::fragment is deprecated and has no effect.
```

Its fairly harmless at this point, but it should probably be removed from the code to remove the red text and be ready for some future version where they remove ensure entirely.

Tommy

**Comment by 3flex** [comment]
Fixed in https://github.com/jfryman/puppet-nginx/pull/757, will be available in the next release published to Forge.

**Comment by TJM** [comment]
awesome!
