### ISSUE TITLE
How to prevent variable substitution

### ISSUE THREAD

**Issue by orbitalmedia** [jfryman/puppet-nginx#795]
Using this puppet code, my goal is to preserve the variable $upstream that is written to the config file. However it is always substituted for the actual value. The reason for the substitution is detailed [here](http://tenzer.dk/nginx-with-dynamic-upstreams/)
  
 $upstream = "http://acme.unix.local"
  nginx::resource::vhost { 'acme.co':
    listen_port => 8080,
    server_name => [
      'www.acme.co'
    ],
    proxy       => "$upstream", 
  }

This is intended ,
  location / {
    proxy_pass            $upstream;
 }

Unfortunately I am getting this result ,
  location / {
    proxy_pass            http://acme.unix.local;
 }

Any suggestions welome

**Comment by 3flex** [comment]
This is Puppet interpolating the string. See https://docs.puppet.com/puppet/latest/reference/lang_variables.html#interpolation

If you don't want it to interpolate and pass `$upstream` as is then surround it with single quotes, i.e. `proxy => '$upstream'`, or escape the dollar sign so the string isn't treated as a variable: `proxy => "\$upstream"`
