### ISSUE TITLE
Subdir for ssl certs

### ISSUE THREAD

**Issue by igoraj** [jfryman/puppet-nginx#80]
If you have a lot of SSL vhosts /etc/nginx tends to be overcrowded with *.crt and *.key files. Just for housekeeping sake I think it would be better to create a subdir under ${nginx::params::nx_conf_dir} e.g. ${nginx::params::nx_conf_dir}/ssl and keep all cert files there, or even make that one a separate param e.g. ${nginx::params::nx_ssl_cert_dir} or something.

What do you guys think about this?

**Comment by 3flex** [comment]
Hi, please add any relevant comments to #599 regarding how the module will treat SSL certificates going forward.
