### ISSUE TITLE
concat::fragment $ensure deprecated

### ISSUE THREAD

**Issue by strarsis** [jfryman/puppet-nginx#802]
````
The $ensure parameter to concat::fragment is deprecated and has no effect.
````
So the $ensure parameters could be now safely removed 
from concat::fragment ressources in this module?

Thanks and 
with best regards

**Comment by 3flex** [comment]
Duplicate of https://github.com/jfryman/puppet-nginx/issues/759

Will be fixed in the next Forge release.

**Comment by pcarrilloj** [comment]
When will be released this change?
