### ISSUE TITLE
add_header doesn't support headers properly

### ISSUE THREAD

**Issue by Spechal** [jfryman/puppet-nginx#803]
The add_header call needs to wrap things in quotes or nginx freaks out.

https://github.com/jfryman/puppet-nginx/blob/56e1c591bf5bfd06c34782c66953b3bc4b10fafa/templates/vhost/vhost_ssl_header.erb#L134

https://github.com/jfryman/puppet-nginx/blob/56e1c591bf5bfd06c34782c66953b3bc4b10fafa/templates/vhost/vhost_header.erb#L131

**Comment by 3flex** [comment]
Do you have example error output from nginx? nginx documentation doesn't mention quotes being required.

**Comment by Spechal** [comment]
I can generate one.  If you have a header with a space in the content, nginx will generate an invalid arguments error.

-Travis

**Comment by 3flex** [comment]
Ah, that makes sense.

I've restarted the failed build, it should pass now. I'll go ahead and merge then. Thanks!
