### ISSUE TITLE
internal location

### ISSUE THREAD

**Issue by nnovikov** [jfryman/puppet-nginx#808]
Puppet generate`internal true;` instead of `internal;`. As consequence nginx config test fails.

**Comment by olevole** [comment]
@nnovikov Where are you see "internal true;" and what version you use? Check out https://github.com/jfryman/puppet-nginx/blob/master/templates/vhost/location_header.erb#L3 line if you talking about  virtualhost. In my cases looks like all fine (from hiera):
~~~
nginx::nginx_locations:
  'static':
     ...
     internal: true
~~~

produced:
~~~
location { 
   ...
   internal;

}
~~

**Comment by nnovikov** [comment]
I had mistake in hiera. All works fine.
