### ISSUE TITLE
duplicate MIME type "text/html"

### ISSUE THREAD

**Issue by hostingnuggets** [jfryman/puppet-nginx#810]
With a pretty basic and standard nginx config I get the following warning message in /var/log/nginx/error.log:

```
[warn] 31043#31043: duplicate MIME type "text/html" in /etc/nginx/nginx.conf:39
```

I guess with nginx 1.10 this MIME type is already included by default and does not need to be defined automatically under the gzip_type parameters.

**Comment by 3flex** [comment]
Fixed in #765.

Available in master branch, but not yet in Forge. @jfryman can you please release a new version?
