### ISSUE TITLE
nginx_version fact not confined

### ISSUE THREAD

**Issue by ekingme** [jfryman/puppet-nginx#814]
The nginx_version fact is not confined.  If you run puppet interactively on windows with this module installed a dialog will pop up and require interaction.  If the puppet agent runs silently it will hang indefinitely.

**Comment by igalic** [comment]
what exactly is the prompt that you're getting?

**Comment by ekingme** [comment]
It is a Windows installer dialog that is asking where I'd like to unpack the Nginx files.  It looks like it is trying to install Nginx.  Admittedly, we have Nginx installed in a non-standard place, so I'm not exactly sure what it's attempting to do.

We don't receive the dialog on a machine without Nginx.

![nginx1](https://cloud.githubusercontent.com/assets/1047875/16270189/75f33a1a-3863-11e6-906b-b5ba7825d087.png)

**Comment by igalic** [comment]
does that module have an (auto)require for package installs somewhere?
or does `which` on windows do something similar like some linux shells' command-missing? but slightly more zealous ;)

**Comment by 3flex** [comment]
Somewhat related - does this module even work on Windows? nginx itself is beta on Windows, and this module has never been tested on that OS. I can't recall any PRs that added any kind of support.

I'm inclined to close this and the related PR in favour of a PR that provides proper support.

**Comment by ekingme** [comment]
The module does not say it supports Windows. Nor do I need or want it to at the moment. But because we have plugin sync enabled, the fact he's copied everywhere and the which seems to cause issues on Windows where I have Nginx installed. The best way I could find to prevent that was to confine the fact.
