### ISSUE TITLE
Debian package source URL should be overridable. 

### ISSUE THREAD

**Issue by mmattice** [jfryman/puppet-nginx#831]
I have some heavily firewalled internal hosts that are permitted to access an approx based Debian package cache.  I'd like to be able to point this at `deb http://mirror.internaldomain:9999/nginx` and continue to use the rest of the module without forking it internally.

**Comment by 3flex** [comment]
As long as the repository is setup in apt's sources.list I'm not quite sure why the module would have to be forked to install the package.

You can set the module not to setup the nginx.org repository by setting `manage_repo` to `false`. The package would then be installed from whichever repositories are setup on your system.

If the package name is not `nginx` you can set `package_name` to whatever the package is called in your repository.

Let me know if I've missed something! But the module should already allow for what you've described.

**Comment by mmattice** [comment]
That seems reasonable.  Thanks.
