### ISSUE TITLE
Passenger Enterprise

### ISSUE THREAD

**Issue by stephen-kainos** [jfryman/puppet-nginx#848]
Anyone used this module with passenger enterprise? 

I've got it working with the open source passenger but I can't see a way to override the apt source for the passenger module.

**Comment by 3flex** [comment]
@stephen-kainos it's currently not possible to override the apt source for the passenger module.

if you want to load the package from a different source, set $manage_repo to false, and specify your own apt source for passenger.

**Comment by stephen-kainos** [comment]
thanks @3flex, I'll give that a go
